data dm.product_dm;
  attrib PROD_HIER_SK length=6;
  attrib PROD_ID length=$32;
  attrib PROD_NM length=$40;
  attrib STD_HIER_PROD_LVL length=4;
  attrib PROD_DESC length=$100;
  attrib PROD_INTRODUCTION_DT length=8 format=DATE9. informat=DATE9.;
  attrib PROD_DISCONTINUED_DT length=8 format=DATE9. informat=DATE9.;
  attrib VOLUME length=8 format=NLNUM12.2 informat=NLNUM12.2;
  attrib VOLUME_BASE_UOM length=$20;
  attrib BRAND_NM length=$40;
  attrib MIN_INV_LVL length=8 format=NLNUM12.2 informat=NLNUM12.2;
  attrib STD_HIER_LEAF_NODE_FLG length=4;
  attrib MODEL_PROD_FLG length=4;
  attrib CREATED_DTTM length=8 label='CREATED_DTTM' format=NLDATM21. informat=NLDATM21.;
  attrib CHANGE_FLG length=$1;
  stop;
run; 

data dm.geography_dm;
  attrib GEO_HIER_SK length=4;
  attrib GEO_ID length=$32;
  attrib GEO_NM length=$40;
  attrib STD_HIER_GEO_LVL length=4;
  attrib FACILITY_TYPE length=4;
  attrib SIZE_OF_FACILITY length=8 format=NLNUM12.2 informat=NLNUM12.2;
  attrib OPEN_DT length=8 format=DATE9. informat=DATE9.;
  attrib CLOSING_DT length=8 format=DATE9. informat=DATE9.;
  attrib STREET_ADDRESS length=$100;
  attrib CITY length=$20;
  attrib STATE length=$20;
  attrib ZIP_CODE length=$20;
  attrib COUNTRY length=$20;
  attrib STD_HIER_LEAF_NODE_FLG length=4;
  attrib CREATED_DTTM length=8 format=NLDATM21. informat=NLDATM21.;
  stop;
run;

data dm.sales_fact;
  attrib PROD_HIER_SK length=4;
  attrib GEO_HIER_SK length=4;
  attrib DATE_SK length=4;
  attrib SALES_QTY length=4;
  attrib SALES_AMT length=4;
  stop;
run;